version: "3"

services:
  www:
    image: nginx:1.13.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./example/nginx-services.conf:/etc/nginx/conf.d/default.conf
      - ./example/index.html:/var/www/public/index.html
      - ./example/custom/output/report:/var/www/public/report


  verify:
    build: .
    environment:
      - TEST_URL=http://www
      - SELENIUM_HOST=selenium_hub
      - SELENIUM_PORT=4444
      - REPORT_THEME=simple
      - VERBOSE=1

    depends_on:
      - www
      - selenium_hub
    volumes:
      - ./example/custom:/app/custom
    links:
      - selenium_hub:selenium_hub

  #
  # Browser virtualization integration testing
  #
  selenium_hub:
    image: selenium/standalone-chrome-debug
    privileged: true
    depends_on:
      - www
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - "uploads:/uploads"
volumes:
  uploads:
